### ISSUE TITLE
Pomysł :D

### ISSUE THREAD

**Issue by Butipsal** [YourEmpire/YourEmpire#2]
Eloo , pytałem się na b.pl gdzie zgłaszać pomysły , odesłano mnie tutaj .

Mam pomysł ( o ile już nie było o nim mowy :smile: ) na możliwość obalenia monarchii , ale tylko na serwery .

Czyli jak grasz na serwerze i są te dwa królestwa ( na przykład ) i w każdym jest 5 osób . Oczywiście jak tak planujecie zrobić system serwerów :Smile: . Założę , że w jednym królestwie ( drugie na razie nie potrzebne jest ) . Ja król i 4 innych graczy ( mieszkańców ) , jak wszyscy się zgodzą to w tym systemie można podjąć próbę obalenia monarchii . Jednak , żeby nie było EASY to król ma strażników , na przykład 3 i oni go bronią , a król ucieka albo robi coś innego . Z drugiej strony , żeby nie było HARD to drugie królestwo nie może zaatakować pierwszego :smile_cat: . To na tyle .

**Comment by MCPlayG** [comment]
Gra będzie polegała na tym, że tylko 1 gracz panuje nad swoim narodem. Jednak wprowadzimy do gry jednostki, które będą mogły spróbować obalić monarchię. Zapewne będzie to "Zamachowiec". Dziękuję za pomysł. :+1:
